//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlToSqlServerConverter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMSSQLServerName {
            get {
                return ((string)(this["DefaultMSSQLServerName"]));
            }
            set {
                this["DefaultMSSQLServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMSSQLDatabase {
            get {
                return ((string)(this["DefaultMSSQLDatabase"]));
            }
            set {
                this["DefaultMSSQLDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMSSQLAuthentication {
            get {
                return ((string)(this["DefaultMSSQLAuthentication"]));
            }
            set {
                this["DefaultMSSQLAuthentication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMSSQLUser {
            get {
                return ((string)(this["DefaultMSSQLUser"]));
            }
            set {
                this["DefaultMSSQLUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMSSQLPass {
            get {
                return ((string)(this["DefaultMSSQLPass"]));
            }
            set {
                this["DefaultMSSQLPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMYSQLHost {
            get {
                return ((string)(this["DefaultMYSQLHost"]));
            }
            set {
                this["DefaultMYSQLHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMYSQLDatabase {
            get {
                return ((string)(this["DefaultMYSQLDatabase"]));
            }
            set {
                this["DefaultMYSQLDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMYSQLUser {
            get {
                return ((string)(this["DefaultMYSQLUser"]));
            }
            set {
                this["DefaultMYSQLUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMYSQLPass {
            get {
                return ((string)(this["DefaultMYSQLPass"]));
            }
            set {
                this["DefaultMYSQLPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MySQL ODBC 5.1 Driver")]
        public string DefaultMYSQLDriver {
            get {
                return ((string)(this["DefaultMYSQLDriver"]));
            }
            set {
                this["DefaultMYSQLDriver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultControlfile {
            get {
                return ((string)(this["DefaultControlfile"]));
            }
            set {
                this["DefaultControlfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTextBoxMessage {
            get {
                return ((string)(this["DefaultTextBoxMessage"]));
            }
            set {
                this["DefaultTextBoxMessage"] = value;
            }
        }
    }
}
